/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherLoginRouteImport } from './routes/teacher-login'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherResourcesRouteImport } from './routes/teacher.resources'
import { Route as TeacherLiveRouteImport } from './routes/teacher.live'
import { Route as TeacherCoursesRouteImport } from './routes/teacher.courses'
import { Route as TeacherChaptersRouteImport } from './routes/teacher.chapters'
import { Route as TeacherAnnouncementsRouteImport } from './routes/teacher.announcements'
import { Route as StudentScheduleRouteImport } from './routes/student.schedule'
import { Route as StudentResourcesRouteImport } from './routes/student.resources'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentExamPrepRouteImport } from './routes/student.exam-prep'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentResourcesCategoryRouteImport } from './routes/student.resources.$category'
import { Route as StudentCoursesCourseIdChaptersChapterIdRouteImport } from './routes/student.courses.$courseId.chapters.$chapterId'

const TeacherLoginRoute = TeacherLoginRouteImport.update({
  id: '/teacher-login',
  path: '/teacher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResourcesRoute = TeacherResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLiveRoute = TeacherLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherChaptersRoute = TeacherChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnnouncementsRoute = TeacherAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResourcesRoute = StudentResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamPrepRoute = StudentExamPrepRouteImport.update({
  id: '/exam-prep',
  path: '/exam-prep',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResourcesCategoryRoute =
  StudentResourcesCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => StudentResourcesRoute,
  } as any)
const StudentCoursesCourseIdChaptersChapterIdRoute =
  StudentCoursesCourseIdChaptersChapterIdRouteImport.update({
    id: '/$courseId/chapters/$chapterId',
    path: '/$courseId/chapters/$chapterId',
    getParentRoute: () => StudentCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-login': typeof TeacherLoginRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/exam-prep': typeof StudentExamPrepRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resources': typeof StudentResourcesRouteWithChildren
  '/student/schedule': typeof StudentScheduleRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/chapters': typeof TeacherChaptersRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/resources/$category': typeof StudentResourcesCategoryRoute
  '/student/courses/$courseId/chapters/$chapterId': typeof StudentCoursesCourseIdChaptersChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/teacher-login': typeof TeacherLoginRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/exam-prep': typeof StudentExamPrepRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resources': typeof StudentResourcesRouteWithChildren
  '/student/schedule': typeof StudentScheduleRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/chapters': typeof TeacherChaptersRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/resources/$category': typeof StudentResourcesCategoryRoute
  '/student/courses/$courseId/chapters/$chapterId': typeof StudentCoursesCourseIdChaptersChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-login': typeof TeacherLoginRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/exam-prep': typeof StudentExamPrepRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resources': typeof StudentResourcesRouteWithChildren
  '/student/schedule': typeof StudentScheduleRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/chapters': typeof TeacherChaptersRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/resources/$category': typeof StudentResourcesCategoryRoute
  '/student/courses/$courseId/chapters/$chapterId': typeof StudentCoursesCourseIdChaptersChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/student'
    | '/teacher'
    | '/teacher-login'
    | '/student/courses'
    | '/student/exam-prep'
    | '/student/profile'
    | '/student/resources'
    | '/student/schedule'
    | '/teacher/announcements'
    | '/teacher/chapters'
    | '/teacher/courses'
    | '/teacher/live'
    | '/teacher/resources'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
    | '/student/resources/$category'
    | '/student/courses/$courseId/chapters/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/teacher-login'
    | '/student/courses'
    | '/student/exam-prep'
    | '/student/profile'
    | '/student/resources'
    | '/student/schedule'
    | '/teacher/announcements'
    | '/teacher/chapters'
    | '/teacher/courses'
    | '/teacher/live'
    | '/teacher/resources'
    | '/teacher/students'
    | '/student'
    | '/teacher'
    | '/student/resources/$category'
    | '/student/courses/$courseId/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/student'
    | '/teacher'
    | '/teacher-login'
    | '/student/courses'
    | '/student/exam-prep'
    | '/student/profile'
    | '/student/resources'
    | '/student/schedule'
    | '/teacher/announcements'
    | '/teacher/chapters'
    | '/teacher/courses'
    | '/teacher/live'
    | '/teacher/resources'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
    | '/student/resources/$category'
    | '/student/courses/$courseId/chapters/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  TeacherLoginRoute: typeof TeacherLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher-login': {
      id: '/teacher-login'
      path: '/teacher-login'
      fullPath: '/teacher-login'
      preLoaderRoute: typeof TeacherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/resources': {
      id: '/teacher/resources'
      path: '/resources'
      fullPath: '/teacher/resources'
      preLoaderRoute: typeof TeacherResourcesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/live': {
      id: '/teacher/live'
      path: '/live'
      fullPath: '/teacher/live'
      preLoaderRoute: typeof TeacherLiveRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/courses': {
      id: '/teacher/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/chapters': {
      id: '/teacher/chapters'
      path: '/chapters'
      fullPath: '/teacher/chapters'
      preLoaderRoute: typeof TeacherChaptersRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/announcements': {
      id: '/teacher/announcements'
      path: '/announcements'
      fullPath: '/teacher/announcements'
      preLoaderRoute: typeof TeacherAnnouncementsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/resources': {
      id: '/student/resources'
      path: '/resources'
      fullPath: '/student/resources'
      preLoaderRoute: typeof StudentResourcesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exam-prep': {
      id: '/student/exam-prep'
      path: '/exam-prep'
      fullPath: '/student/exam-prep'
      preLoaderRoute: typeof StudentExamPrepRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/resources/$category': {
      id: '/student/resources/$category'
      path: '/$category'
      fullPath: '/student/resources/$category'
      preLoaderRoute: typeof StudentResourcesCategoryRouteImport
      parentRoute: typeof StudentResourcesRoute
    }
    '/student/courses/$courseId/chapters/$chapterId': {
      id: '/student/courses/$courseId/chapters/$chapterId'
      path: '/$courseId/chapters/$chapterId'
      fullPath: '/student/courses/$courseId/chapters/$chapterId'
      preLoaderRoute: typeof StudentCoursesCourseIdChaptersChapterIdRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
  }
}

interface StudentCoursesRouteChildren {
  StudentCoursesCourseIdChaptersChapterIdRoute: typeof StudentCoursesCourseIdChaptersChapterIdRoute
}

const StudentCoursesRouteChildren: StudentCoursesRouteChildren = {
  StudentCoursesCourseIdChaptersChapterIdRoute:
    StudentCoursesCourseIdChaptersChapterIdRoute,
}

const StudentCoursesRouteWithChildren = StudentCoursesRoute._addFileChildren(
  StudentCoursesRouteChildren,
)

interface StudentResourcesRouteChildren {
  StudentResourcesCategoryRoute: typeof StudentResourcesCategoryRoute
}

const StudentResourcesRouteChildren: StudentResourcesRouteChildren = {
  StudentResourcesCategoryRoute: StudentResourcesCategoryRoute,
}

const StudentResourcesRouteWithChildren =
  StudentResourcesRoute._addFileChildren(StudentResourcesRouteChildren)

interface StudentRouteChildren {
  StudentCoursesRoute: typeof StudentCoursesRouteWithChildren
  StudentExamPrepRoute: typeof StudentExamPrepRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentResourcesRoute: typeof StudentResourcesRouteWithChildren
  StudentScheduleRoute: typeof StudentScheduleRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCoursesRoute: StudentCoursesRouteWithChildren,
  StudentExamPrepRoute: StudentExamPrepRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentResourcesRoute: StudentResourcesRouteWithChildren,
  StudentScheduleRoute: StudentScheduleRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAnnouncementsRoute: typeof TeacherAnnouncementsRoute
  TeacherChaptersRoute: typeof TeacherChaptersRoute
  TeacherCoursesRoute: typeof TeacherCoursesRoute
  TeacherLiveRoute: typeof TeacherLiveRoute
  TeacherResourcesRoute: typeof TeacherResourcesRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAnnouncementsRoute: TeacherAnnouncementsRoute,
  TeacherChaptersRoute: TeacherChaptersRoute,
  TeacherCoursesRoute: TeacherCoursesRoute,
  TeacherLiveRoute: TeacherLiveRoute,
  TeacherResourcesRoute: TeacherResourcesRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  TeacherLoginRoute: TeacherLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
