/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentScheduleRouteImport } from './routes/student.schedule'
import { Route as StudentResourcesRouteImport } from './routes/student.resources'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentExamPrepRouteImport } from './routes/student.exam-prep'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentChapterIdRouteImport } from './routes/student.chapter.$id'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResourcesRoute = StudentResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamPrepRoute = StudentExamPrepRouteImport.update({
  id: '/exam-prep',
  path: '/exam-prep',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentChapterIdRoute = StudentChapterIdRouteImport.update({
  id: '/chapter/$id',
  path: '/chapter/$id',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/student/courses': typeof StudentCoursesRoute
  '/student/exam-prep': typeof StudentExamPrepRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resources': typeof StudentResourcesRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/': typeof StudentIndexRoute
  '/student/chapter/$id': typeof StudentChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/exam-prep': typeof StudentExamPrepRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resources': typeof StudentResourcesRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student': typeof StudentIndexRoute
  '/student/chapter/$id': typeof StudentChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/student/courses': typeof StudentCoursesRoute
  '/student/exam-prep': typeof StudentExamPrepRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resources': typeof StudentResourcesRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/': typeof StudentIndexRoute
  '/student/chapter/$id': typeof StudentChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/student'
    | '/student/courses'
    | '/student/exam-prep'
    | '/student/profile'
    | '/student/resources'
    | '/student/schedule'
    | '/student/'
    | '/student/chapter/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student/courses'
    | '/student/exam-prep'
    | '/student/profile'
    | '/student/resources'
    | '/student/schedule'
    | '/student'
    | '/student/chapter/$id'
  id:
    | '__root__'
    | '/'
    | '/student'
    | '/student/courses'
    | '/student/exam-prep'
    | '/student/profile'
    | '/student/resources'
    | '/student/schedule'
    | '/student/'
    | '/student/chapter/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/resources': {
      id: '/student/resources'
      path: '/resources'
      fullPath: '/student/resources'
      preLoaderRoute: typeof StudentResourcesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exam-prep': {
      id: '/student/exam-prep'
      path: '/exam-prep'
      fullPath: '/student/exam-prep'
      preLoaderRoute: typeof StudentExamPrepRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/chapter/$id': {
      id: '/student/chapter/$id'
      path: '/chapter/$id'
      fullPath: '/student/chapter/$id'
      preLoaderRoute: typeof StudentChapterIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentExamPrepRoute: typeof StudentExamPrepRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentResourcesRoute: typeof StudentResourcesRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentChapterIdRoute: typeof StudentChapterIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCoursesRoute: StudentCoursesRoute,
  StudentExamPrepRoute: StudentExamPrepRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentResourcesRoute: StudentResourcesRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentChapterIdRoute: StudentChapterIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
